#!/bin/sh

name=$1

cat <<EOF > doc/$name
                           Yb  dP    db    88 888888 
                            YbdP    dPYb   88   88   
                             8P    dP__Yb  88   88   
                            dP    dP""""Yb 88   88   

				  yait manual

$name
$(printf '%*s\n' "${#name}" '' | tr ' ' '#')


EOF

if [ "$EDITOR" = "nvim" ]; then
	nvim +'normal! Gi' doc/$name
	exit 0
fi

$EDITOR doc/$name
